LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
LOG_STARTUP = "Starting Nopal Leads API"
LOG_SHUTDOWN = "Shutdown complete"

APP_TITLE = "Nopal Leads API"
APP_DESCRIPTION = "Captura y clasificación de leads desde redes sociales (Meta)"
APP_VERSION = "1.0.0"

HEALTH_STATUS = "ok"
HEALTH_STATUS_KEY = "status"

DEFAULT_OPENAI_MODEL = "gpt-4o-mini"
DEFAULT_DATABASE_URL = "postgresql://postgres:postgres@db:5432/nopal_leads"
DEFAULT_POSTGRES_USER = "postgres"
DEFAULT_POSTGRES_PASSWORD = "postgres"
DEFAULT_POSTGRES_DB = "nopal_leads"
DEFAULT_SESSION_EXPIRY_HOURS = 48
DEFAULT_SESSION_IDLE_TIMEOUT_MINUTES = 10
DEFAULT_SESSION_MAX_DURATION_MINUTES = 30
DEFAULT_MESSAGE_BURST_INACTIVITY_SECONDS = 1.5
DEFAULT_MESSAGE_BURST_MAX_WAIT_SECONDS = 4.0
DEFAULT_MESSAGE_BURST_MAX_MESSAGES = 5
DEFAULT_HANDOFF_IDLE_TIMEOUT_MINUTES = 30
DEFAULT_MAX_CLARIFICATION_ATTEMPTS = 3
DEFAULT_MAX_TOPIC_CHANGES = 2
DEFAULT_BOT_OUTBOUND_EVENT_TTL_SECONDS = 180.0
DEFAULT_META_GRAPH_API_VERSION = "v21.0"
DEFAULT_JWT_ALGORITHM = "HS256"
DEFAULT_JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 480
