from app.constants.units import DEFAULT_NOPAL_UNIT

CATEGORY_LEAD = "lead"
CATEGORY_PROVEEDOR = "proveedor"
CATEGORY_SALUDO = "saludo"
CATEGORY_CONSULTA = "consulta"
CATEGORY_SPAM = "spam"
CATEGORY_AUTO_REPLY = "auto_reply"
CATEGORY_HUMAN_REPLY = "human_reply"

DIRECTION_INBOUND = "inbound"
DIRECTION_OUTBOUND = "outbound"

ORDER_STATUS_DRAFT = "draft"
ORDER_STATUS_COLLECTING = "collecting"
ORDER_STATUS_READY_TO_CONFIRM = "ready_to_confirm"
ORDER_STATUS_CONFIRMED = "confirmed"
ORDER_STATUS_CLOSED = "closed"
ORDER_STATUS_CANCELLED = "cancelled"

CONVERSATION_STATUS_OPEN = "open"
CONVERSATION_STATUS_CLOSED = "closed"

ACTIVE_ORDER_STATUSES: tuple[str, ...] = (
    ORDER_STATUS_DRAFT,
    ORDER_STATUS_COLLECTING,
    ORDER_STATUS_READY_TO_CONFIRM,
)

FINAL_ORDER_STATUSES: tuple[str, ...] = (
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_CLOSED,
    ORDER_STATUS_CANCELLED,
)

PLATFORM_FACEBOOK = "facebook"
PLATFORM_INSTAGRAM = "instagram"
PLATFORM_WHATSAPP = "whatsapp"
PLATFORM_PATTERN = "^(facebook|instagram|whatsapp)$"

PRODUCT_CODE_NOPAL = "nopal"
PRODUCT_NAME_NOPAL = "Nopal"
DEFAULT_QUANTITY_UNIT = DEFAULT_NOPAL_UNIT

FIELD_NOMBRE = "nombre"
FIELD_TELEFONO = "telefono"
FIELD_CANTIDAD = "cantidad"
FIELD_CIUDAD = "ciudad"

DATOS_EXTRAIDOS_PRIMER_MENSAJE = "primer_mensaje"
DATOS_EXTRAIDOS_RESPUESTA = "respuesta"
ORDER_CAPTURE_NOTES_TEMPLATE = "capturado_en:{source}|canal:{platform}"
