MESSAGE_BURST_JOIN_SEPARATOR = "\n"
BUFFER_KEY_TEMPLATE = "{plataforma}:{sender_id}"
AGGREGATED_EVENT_ID_TEMPLATE = "batch:{first}:{last}:{count}"

FLUSH_REASON_INACTIVITY = "inactivity_window"
FLUSH_REASON_MAX_WAIT = "max_wait"
FLUSH_REASON_MAX_MESSAGES = "max_messages"
FLUSH_REASON_SHUTDOWN = "shutdown"

MIN_INACTIVITY_SECONDS = 0.1
MIN_MAX_WAIT_SECONDS = 0.2
MIN_MAX_MESSAGES = 1
