LOG_BUFFER_DISABLED = "Message burst buffer disabled; processing inbound messages immediately"
LOG_BUFFER_ENABLED_TEMPLATE = "Message burst buffer enabled (inactivity=%.2fs max_wait=%.2fs max_messages=%s)"
LOG_BUFFER_EVENT_ALREADY_PENDING_TEMPLATE = "Event already pending in buffer: %s"
LOG_BUFFER_EVENT_BUFFERED_TEMPLATE = "Buffered event %s in %s (%s/%s)"
LOG_BUFFER_FLUSH_TEMPLATE = "Flushing buffer %s (reason=%s, events=%s)"
LOG_BUFFER_FLUSHED_TEMPLATE = "Flushed buffer %s with %s event(s)"
LOG_BUFFER_BACKGROUND_FLUSH_FAILED_TEMPLATE = "Background flush failed for buffer %s"
LOG_BUFFER_TASK_CANCELLED_TEMPLATE = "Buffer task cancelled for %s"
LOG_BUFFER_SHUTDOWN_FLUSH_TEMPLATE = "Flushing %s pending buffer(s) during shutdown"
LOG_BUFFER_SHUTDOWN_DRAINED = "Message burst buffer drained"
