WEBHOOK_TAG = "webhook"
INTERNAL_TAG = "internal"

WEBHOOK_PATH = "/webhook/meta"
HEALTH_PATH = "/health"
CLASSIFY_PATH = "/classify"
EXTRACT_PATH = "/extract"
RESPOND_PATH = "/respond"
SESSION_PATH = "/session"
HANDOFF_PATH = "/handoff"
REPORT_LEADS_PATH = "/reports/leads"
AUTH_LOGIN_PATH = "/auth/login"

WEBHOOK_RATE_LIMIT = "60/minute"

HUB_MODE_ALIAS = "hub.mode"
HUB_VERIFY_TOKEN_ALIAS = "hub.verify_token"
HUB_CHALLENGE_ALIAS = "hub.challenge"
HUB_MODE_SUBSCRIBE = "subscribe"

LOG_POST_CLASSIFY = "POST /classify"
LOG_POST_EXTRACT = "POST /extract"
LOG_POST_RESPOND_TEMPLATE = "POST /respond for sender=%s"
LOG_POST_SESSION_TEMPLATE = "POST /session for sender=%s"
LOG_POST_HANDOFF_TEMPLATE = "POST /handoff for sender=%s locked=%s"
LOG_GET_REPORT_LEADS = "GET /reports/leads"
LOG_POST_AUTH_LOGIN_TEMPLATE = "POST /auth/login for username=%s"
LOG_WEBHOOK_VERIFY_TEMPLATE = "Meta webhook verification attempt (mode=%s)"
LOG_WEBHOOK_VERIFIED = "Webhook verified successfully"
LOG_WEBHOOK_VERIFY_FAILED = "Webhook verification failed"
LOG_WEBHOOK_DUPLICATE_TEMPLATE = "Duplicate event ignored: %s"
LOG_WEBHOOK_BUFFERED_TEMPLATE = "Buffered inbound event: %s"
